apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../kustomize/
- network-policy-agent.yaml
- serviceaccount-agent-ns.yaml
- role-agent-ns.yaml
- rolebinding-agent-ns.yaml
- rolebinding-agent-ns-statuswrite.yaml
