apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mechanic-agent-ns-statuswrite
  namespace: mechanic
subjects:
- kind: ServiceAccount
  name: mechanic-agent-ns
  namespace: mechanic
roleRef:
  kind: ClusterRole
  name: mechanic-agent
  apiGroup: rbac.authorization.k8s.io
