{{- if and .Values.rbac.create (eq .Values.watcher.agentRBACScope "namespace") }}
{{- $root := . }}
{{- range $ns := splitList "," .Values.watcher.agentWatchNamespaces }}
{{- if $ns }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mechanic.fullname" $root }}-agent-ns
  namespace: {{ $ns | trim }}
  labels:
    {{- include "mechanic.labels" $root | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "mechanic.agentNSSAName" $root }}
  namespace: {{ $root.Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "mechanic.fullname" $root }}-agent-ns
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
{{- end }}
