apiVersion: v1
kind: Secret
metadata:
  name: mechanic-agent-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mechanic.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "mechanic.agentSAName" . }}
type: kubernetes.io/service-account-token
