apiVersion: v2
name: mendabot
description: Kubernetes-native SRE remediation bot
type: application
version: 0.1.0
appVersion: v0.3.2
kubeVersion: ">=1.28.0-0"
keywords:
  - kubernetes
  - sre
  - remediation
  - gitops
  - ai
home: https://github.com/lenaxia/k8s-mendabot
sources:
  - https://github.com/lenaxia/k8s-mendabot
maintainers:
  - name: lenaxia
    url: https://github.com/lenaxia
