{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mendabot.fullname" . }}-crd-upgrader
  labels:
    {{- include "mendabot.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "mendabot.fullname" . }}-crd-upgrader
subjects:
- kind: ServiceAccount
  name: {{ include "mendabot.fullname" . }}-crd-upgrader
  namespace: {{ .Release.Namespace }}
{{- end }}
