apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mendabot.fullname" . }}-crd-upgrader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mendabot.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "mendabot.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "mendabot.fullname" . }}-crd-upgrader
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: kubectl
        image: registry.k8s.io/kubectl:v1.28.16
        command: ["kubectl", "apply", "-f", "/crds/remediationjob.yaml"]
        env:
        - name: HOME
          value: /tmp
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        volumeMounts:
        - name: crd
          mountPath: /crds
        - name: kube-cache
          mountPath: /tmp
      volumes:
      - name: crd
        configMap:
          name: {{ include "mendabot.fullname" . }}-crd-upgrader
      - name: kube-cache
        emptyDir: {}
