{{- if and .Values.rbac.create (eq .Values.watcher.agentRBACScope "namespace") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mendabot.agentNSSAName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mendabot.labels" . | nindent 4 }}
{{- end }}
